version: '3.1'

services:

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: mudar123
#    healthcheck:
#        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#        timeout: 20s
#        retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - '127.0.0.1:8080:80'
    environment:
        - PMA_ARBITRARY=1
    links:
        - mysql

  web:
      image: nginx:latest
      restart: always
      ports:
          - "127.0.0.1:80:80"
      volumes:
          - ./:/www
          - ./default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php

  php:
      container_name: php-fpm
      build: .
      volumes:
          - ./:/www
#      command: bash -c "sleep 30; cd /www; chmod 777 -R storage; php artisan key:generate; php artisan migrate;"
#      command: bash -c "cd /www; chmod 777 -R storage; php artisan key:generate; php artisan migrate;"      
      links:
          - mysql
#      depends_on:
#          - mysql
#              condition: service_healthy

  phpqa:
      image: jakzal/phpqa:php7.4
      container_name: phpqa
      volumes:
          - ./:/www
      working_dir: /www
      command: bash -c "composer install"            

